transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/shift_rwos.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/sbox.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/reg.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/gfmult_by2.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/add_round_key.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/sub_byte.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/key_sch_round_function.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/controller.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/column_calculator.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/mix_columns.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/key_schedule.vhd}
vcom -93 -work work {C:/Users/LEGION/Desktop/INDUSTRIALES/MOVILIDAD/COSITAS_DE_CS/ASIGNATURAS/2A/SEMESTRE_2/POLE_PROJET_P11_IOT/HARDWARE_SECURITY_PART/UARTX/AES_PROJECT/INTEGRATION_PROJECT/aes_enc.vhd}

